# Fault-injection into details service.
# Most requests to details:v1 will abort with one of three error codes.
# Those requests whose request-id does not match any regex definition below will be OK.
#
# last tested on Istio 1.10
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: details-abort-vs
spec:
  hosts:
  - details
  http:
  - match:
    - headers:
        x-request-id:
          regex: "^[1234].*"
    route:
    - destination:
        host: details
        subset: details-abort-dr-subset-v1
    fault:
      abort:
        httpStatus: 551
        percentage:
          value: 100
  - match:
    - headers:
        x-request-id:
          regex: "^[5678].*"
    route:
    - destination:
        host: details
        subset: details-abort-dr-subset-v1
    fault:
      abort:
        httpStatus: 552
        percentage:
          value: 100
  - match:
    - headers:
        x-request-id:
          regex: "^[90ab].*"
    route:
    - destination:
        host: details
        subset: details-abort-dr-subset-v1
    fault:
      abort:
        httpStatus: 553
        percentage:
          value: 100
  - route:
    - destination:
        host: details
        subset: details-abort-dr-subset-v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: details-abort-dr
spec:
  host: details
  subsets:
  - name: details-abort-dr-subset-v1
    labels:
      version: v1

